import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { request, type Schema } from "./api";
import { useData } from "./data";
import { Panel, Banner, Facts, date } from "./ui";
import { ValidationFinalCheck } from "./validation-final-check";

export function LabCompletion({ job }: { job: Schema["JobView"] }) {
  const { data, changed, loading, error: sourceError } = useData();
  const [event, setEvent] = useState<Schema["LabCompletion"] | null>(null);
  const [identity, setIdentity] = useState(false),
    [busy, setBusy] = useState(false),
    [error, setError] = useState("");
  const lock = useRef(false);
  async function read() {
    const value = await request<Schema["LabCompletion"]>(
      `/validation/jobs/${encodeURIComponent(job.id)}/completion`,
      "reader",
    );
    setEvent(value);
    return value;
  }
  useEffect(() => {
    void read().catch(() => {});
  }, [job.id]);
  async function publish() {
    if (lock.current || !identity) return;
    lock.current = true;
    setBusy(true);
    setError("");
    try {
      const response = await fetch(
        `/api/v1/validation/jobs/${encodeURIComponent(job.id)}/synthetic-result`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer demo-lab-local-only",
            "Idempotency-Key": "lab_completion_" + job.id,
          },
          body: JSON.stringify({ expected_plan_digest: job.plan_digest }),
        },
      );
      const receipt = await response.json();
      if (!response.ok)
        throw new Error(
          receipt.error?.message || "Lab event was not confirmed.",
        );
      const actual = await read();
      if (
        actual.id !== receipt.id ||
        actual.result_digest !== receipt.result_digest
      )
        throw new Error(
          "Lab readback mismatch. Retry the same synthetic event.",
        );
      await changed();
    } catch (e) {
      setError(
        (e as Error).message + " Refresh or retry to recover the same result.",
      );
    } finally {
      lock.current = false;
      setBusy(false);
    }
  }
  if (job.change_id !== "CR-017") return null;
  const completion = event || job.completion;
  return (
    <div
      role="region"
      aria-label={
        completion
          ? "Published validation result"
          : "Final check before publishing"
      }
    >
      <Panel
        title={
          completion
            ? "Published validation result"
            : "Final check before publishing"
        }
        className="lab-completion"
      >
        {completion ? (
          <>
            <Banner tone="good">
              The synthetic passing result is published. Review the recorded
              evidence below.
            </Banner>
            <Facts
              items={[
                ["Lab event", "Completed · Result received"],
                ["Generated by", "Demo lab action"],
                ["Source", completion.source_reference],
                ["Simulated completion", date(completion.completed_at)],
                ["Recorded at (wall clock)", date(completion.recorded_at)],
                ["Original booking", "Preserved · " + job.id],
                [
                  "CR-017 status",
                  "Technical completion recorded automatically",
                ],
              ]}
            />
            <Link
              className="button"
              to={"/validation/results/" + completion.result_id}
            >
              View validation result
            </Link>{" "}
            <Link
              className="button"
              to="/control/programs/PRG-A17/cases/CR-017"
            >
              View completed CR-017
            </Link>
          </>
        ) : (
          <>
            <ValidationFinalCheck
              job={job}
              caseData={data?.cases.find((c) => c.change.id === job.change_id)}
              unavailable={loading || !!sourceError}
            />
            <div className="vfc-publish">
              <div>
                <label>
                  <input
                    type="checkbox"
                    checked={identity}
                    onChange={(e) => setIdentity(e.target.checked)}
                  />{" "}
                  Demo identity · Lab operator for this synthetic event
                </label>
                <p className="muted">
                  Synthetic lab event; agents do not run physical tests.
                  Engineering authority is unchanged.
                </p>
              </div>
              <button
                className="primary"
                disabled={!identity || busy || loading || !!sourceError}
                onClick={() => void publish()}
              >
                {busy ? "Publishing…" : "Publish synthetic result"}
              </button>
            </div>
          </>
        )}
        {error && (
          <p role="alert" className="vfc-error">
            {error}
          </p>
        )}
      </Panel>
    </div>
  );
}
